module.exports= Object.freeze({
    DB_MOBILE: 'mobile',
    DB_FNAME: 'fname',
    DB_LNAME:'lname',
    DB_EMAIL: 'email',
    DB_PHOTOURL: 'photourl',
    DB_USERTYPE:'usertype',
    DB_PICKUPLOC:'pickuploc',
    DB_PICKUPADD: 'pickupadd',
    DB_PICKUPLATLONG:'pickuplatlong',
    DB_PICKUPNAME: 'pickupname',
    DB_PICKUPPHONE: 'pickupphone',
    DB_DROPLOC:'droploc',
    DB_DROPADD: 'dropadd',
    DB_DROPLATLONG: 'droplatlong',
    DB_DROPNAME :'dropname',
    DB_DROPPHONE: 'dropphone',
    DB_STATUS:'status',
    DB_VENDORNAME: 'vname',
    DB_VENDORABOUT: 'vabout',
    DB_VENDORLOGO: 'logo',
    DB_ISVENDOR: 'isvendor',
    DB_WEIGHT:  "weight",
    DB_DISTANCE:  "distance",
    DB_PRICE: "price",
    DB_DELINSTRUCTION: "delinstruction",
    DB_PAYMENT : "payment",
    DB_NOTITOKEN: "notitoken",
    DB_WALLET: "wallet",
    DB_DELPARTNER: "del_partner",
    DB_JOINNINGDATE: "joinning_date",
    DB_ROUNDTRIP:"Round trip",
    DB_PRICEDISTRIBUTION:"price_distribution",
    DB_ROUNDTRIPCOL:"round_trip",
    DB_SPECIALUSER:"special_user"
});
